channels:
  - conda-forge

dependencies:
  - python=3.10.0                 # https://pyreadiness.org/3.10
  - uv=0.11.7                      # https://pypi.org/project/uv
  - pip:
    - rpaframework==31.2.0        # https://rpaframework.org/releasenotes.html
    - robocorp==3.1.1             # https://pypi.org/project/robocorp
    - robocorp-browser==2.4.0     # https://pypi.org/project/robocorp-browser